//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegisEVote.ServiciosWeb.ObjetosNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public int IdVoto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdVotante { get; set; }
        public Nullable<int> IdCandidato { get; set; }
    
        public virtual PersonaRol Candidato { get; set; }
        public virtual PersonaRol Votante { get; set; }
    }
}
